### ISSUE TITLE
释放错误 

### ISSUE THREAD

**Issue by lynch9983** [yangyxd/wke-for-delphi#3]
1. 我用 XE 10 编译 wkeCallNativeFun 这个例子，使用完全没问题，但释放会报错“无效的窗口句柄”。
但 bin.rar 里的是好的。

2. OnwkeLoadingFinishCallback 函数中 FUrl := AUrl; 是无效的。

**Comment by lelandyang** [comment]
该Wrapper的作者似乎没有做版本兼容，也无意于此。估计需要你自行修复版本问题。
参见： https://github.com/yangyxd/wke-for-delphi/issues/1

**Comment by pzx521521** [comment]
关闭报错怎么改?  一头雾水

**Comment by lynch9983** [comment]
> 关闭报错怎么改? 一头雾水

我这用法简单，直接把 WkeBrowser.pas 放弃了， 直接用 Wke.pas 创建、加载和释放。有时间再看释放的问题了，可能是哪重复释放了。

**Comment by pzx521521** [comment]
@lynch1983 TKS!
